<a href="https://colab.research.google.com/github/wonwookim/DataMining/blob/main/data_preprocessing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Library : Numpy

In [1]:
import numpy as np

In [2]:
ar = np.array([1,2,3,4,5,6,7,8,9])
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [5]:
data1 = [1,2,'3']
data1

[1, 2, '3']

In [7]:
data2 = np.array([0,1,2,'3']) #string 값이 들어가면 다 string 처리
data2

array(['0', '1', '2', '3'], dtype='<U21')

In [8]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = []
for i in data:
  answer.append(i * 2)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

2 * a * b

array([ 8, 20, 36])

In [16]:
a == 1 # array와 특정 값을 비교하는 것은 해당 행렬 안의 값 모두 비교하여 결과를 도출

array([ True, False, False])

In [24]:
d = np.array([[1,2,3], [4,5,6]])
print(f'd = {d}\n d의 차원 : {d.ndim}\n d의 shape : {d.shape}\n d[1] : {d[1]}\n d의 1행 2,3열 : {d[1,1:]}')

d = [[1 2 3]
 [4 5 6]]
 d의 차원 : 2
 d의 shape : (2, 3)
 d[1] : [4 5 6]
 d의 1행 2,3열 : [5 6]


##Pandas
* Pandas = Panel Data의 줄임말로 여러 개체들을 복수의 시간에 걸쳐서 추적하여 얻는 데이터
* data science, data analysis, machine learning 에서 주로 사용
* numpy기반 라이브러리
* 행,열 존재하는 데이터프레임 형식 데이터 다루기 편함
* 시계열, 비시계열 데이터를 함께 다룰 수 있음
* Series, DataFrame은 해당 라이브러리의 주된 특징임

In [25]:
import pandas as pd

###Series

In [26]:
ser = pd.Series([1,2,3])
ser

0    1
1    2
2    3
dtype: int64

In [29]:
ser2 = pd.Series([1,2,3,4,5,6], index = ['a','b','c','d','e','f'])

ser2 #series는 무조건 1차원만 사용 가능

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [39]:
print(f'ser2의 합: {ser2.sum()}\
        \nser2의 최소값 : {ser2.min()}\
        \nser2의 최대값 : {ser2.max()}\
        \nser2의 평균 : {ser2.mean()}\
        \nser2의 표준편차 : {ser2.std()}\
        \nser2의 왜도 : {ser2.skew()}\
        \nser2의 첨도 : {ser2.kurt()}\
        \nser2의 최대값 위치 : {ser2.idxmax()}\
        \nser2의 포함 여부 검사 : \n{ser2.isin([1,2,3,4])}\
      ')

ser2의 합: 21        
ser2의 최소값 : 1        
ser2의 최대값 : 6        
ser2의 평균 : 3.5        
ser2의 표준편차 : 1.8708286933869707        
ser2의 왜도 : 0.0        
ser2의 첨도 : -1.2000000000000002        
ser2의 최대값 위치 : f        
ser2의 포함 여부 검사 : 
a     True
b     True
c     True
d     True
e    False
f    False
dtype: bool      


In [42]:
ser2[0]
ser2['c']
ser2.c

3

In [44]:
s1_no = pd.Series({
    '서울' : 7892,
    '인천' : 9283,
    '대전' : 6633,
    '광주' : 9211
})
s2_no = pd.Series({
    '전주' : 1923,
    '인천' : 1552,
    '대전' : 2270,
    '가평' : 3453
})
s2_no

전주    1923
인천    1552
대전    2270
가평    3453
dtype: int64

In [45]:
s1_yes = pd.Series({
    '서울' : 7892,
    '인천' : 9283,
    '대전' : 6633,
    '광주' : 9211
}, index = ['서울', '인천', '대전', '광주'])
s2_yes = pd.Series({
    '전주' : 1923,
    '인천' : 1552,
    '대전' : 2270,
    '가평' : 3453
}, index= ['인천', '대전', '전주', '가평'])
s2_yes

인천    1552
대전    2270
전주    1923
가평    3453
dtype: int64

In [46]:
s2_yes - s1_yes # 없는 값이 있으면 nan으로 표시

가평       NaN
광주       NaN
대전   -4363.0
서울       NaN
인천   -7731.0
전주       NaN
dtype: float64

In [47]:
s2_yes.values - s1_yes.values

array([-6340, -7013, -4710, -5758])

###DataFrame

In [48]:
pd.DataFrame([[1,2,2], [3,3,4], [3,4,5], [6,2,4]])

0  1  2
0  1  2  2
1  3  3  4
2  3  4  5
3  6  2  4

In [50]:
pd.DataFrame({'aa' : [1,2,3], 
              'bb' : [4,5,6]}, index= [1,2,3])

aa  bb
1   1   4
2   2   5
3   3   6

In [51]:
pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ['aa', 'bb','cc'], index = ['a','b','c'])

aa  bb  cc
a   1   2   3
b   4   5   6
c   7   8   9

In [52]:
data = {'2015' : [990, 344, 289, 246],
        '2010' : [963, 339, 263, 243],
        '2005' : [976, 365, 246, 247],
        '2000' : [985, 365, 246, 247],
        '지역' : ['수도권', '경상권', '수도권', '경상권'],
        '2010 - 2015 증가율' : [0.028, 0.016, 0.098, 0.014]}
columns = ['지역', '2015', '2010', '2005', '2000', '2010 - 2015 증가율']
index = ['서울', '부산', '인천', '대구']
df = pd.DataFrame(data, columns = columns, index = index)
df

지역  2015  2010  2005  2000  2010 - 2015 증가율
서울  수도권   990   963   976   985            0.028
부산  경상권   344   339   365   365            0.016
인천  수도권   289   263   246   246            0.098
대구  경상권   246   243   247   247            0.014

In [56]:
print(f"df의 행렬 값 : {df.values} \
        \ndf의 컬럼 값 : {df.columns} \
        \ndf의 인덱스 값 : {df.index}\
        \ndf['지역'] : {df[['지역']]}")

df의 행렬 값 : [['수도권' 990 963 976 985 0.028]
 ['경상권' 344 339 365 365 0.016]
 ['수도권' 289 263 246 246 0.098]
 ['경상권' 246 243 247 247 0.014]]         
df의 컬럼 값 : Index(['지역', '2015', '2010', '2005', '2000', '2010 - 2015 증가율'], dtype='object')         
df의 인덱스 값 : Index(['서울', '부산', '인천', '대구'], dtype='object')        
df['지역'] :      지역
서울  수도권
부산  경상권
인천  수도권
대구  경상권


In [57]:
df[['지역']]

지역
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [63]:
df2 = pd.DataFrame(np.arange(0,12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [67]:
df['서울':'대구']

지역  2015  2010  2005  2000  2010 - 2015 증가율
서울  수도권   990   963   976   985            0.028
부산  경상권   344   339   365   365            0.016
인천  수도권   289   263   246   246            0.098
대구  경상권   246   243   247   247            0.014

In [68]:
df2[[1,2]]

1   2
0  1   2
1  5   6
2  9  10

In [72]:
df3 = pd.DataFrame(np.arange(9,21).reshape(3,4), 
                   index = ['a', 'b','c'], 
                   columns=['A','B','C','D'])
df3

A   B   C   D
a   9  10  11  12
b  13  14  15  16
c  17  18  19  20

In [77]:
df3.loc['a' : 'c', 'A' : 'C']

A   B   C
a   9  10  11
b  13  14  15
c  17  18  19

In [80]:
df3.iloc[-1] * 2

A    34
B    36
C    38
D    40
Name: c, dtype: int64